"""Orchestrates one conversational turn through the agent."""

from __future__ import annotations

from collections.abc import AsyncIterator

from agents import Runner
from openai.types.responses import ResponseTextDeltaEvent

from app.agent.assistant import build_agent
from app.agent.context import Channel, RunContext
from app.agent.session import RedisSession
from app.services.media.types import AgentStreamEvent


async def remember_assistant_message(conversation_id: str, text: str) -> None:
    """Append an app-spoken assistant message to the Agents SDK session history.

    Voice-call prompts such as the welcome and silence re-prompt are spoken by the media
    session directly, not generated by ``Runner``. Recording them keeps short caller replies
    like \"yes\" or \"no\" grounded in the prompt the caller just heard.
    """

    normalized = text.strip()
    if not normalized:
        return
    await RedisSession(conversation_id).add_items(
        [{"role": "assistant", "content": normalized}]
    )


async def run_turn(
    message: str,
    phone_number: str,
    conversation_id: str | None = None,
    channel: Channel = "api",
    business_number: str | None = None,
) -> tuple[str, str]:
    """Run one guest message and return (reply, conversation_id).

    Short-term context is threaded via a Redis-backed session keyed by the conversation id
    (defaulting to the guest's phone number). The phone number, channel, and business number
    are supplied to tools through trusted run context, never as model arguments.
    """
    conv_id = conversation_id or phone_number
    session = RedisSession(conv_id)
    result = await Runner.run(
        build_agent(),
        message,
        session=session,
        context=RunContext(
            phone_number=phone_number, channel=channel, business_number=business_number
        ),
    )
    return result.final_output, conv_id


async def run_turn_events(
    message: str,
    phone_number: str,
    conversation_id: str | None = None,
    channel: Channel = "api",
) -> AsyncIterator[AgentStreamEvent]:
    """Stream one guest turn as structured events (voice loop, feature 005 / FR-006).

    Maps ``Runner.run_streamed(...).stream_events()`` onto ``AgentStreamEvent`` so the media
    session can react to tool calls (speak a tailored filler) distinctly from reply text
    (pipe to TTS). See ``specs/005-fix-voice-call-flow/contracts/agent-turn-events.md``:

    - ``raw_response_event`` carrying a non-empty ``ResponseTextDeltaEvent`` → ``text_delta``.
    - ``run_item_stream_event`` with ``item.type == "tool_call_item"`` → ``tool_call`` (a tool
      is about to run; the name comes from ``item.raw_item.name``).
    - ``run_item_stream_event`` with ``item.type == "tool_call_output_item"`` → ``tool_output``
      (the tool returned; ``ok`` marks success).

    The stream is consumed to completion so Redis session persistence finishes (Agents SDK
    streaming docs). Same trusted-context guarantee as ``run_turn``: the phone number never
    becomes a model argument.
    """
    conv_id = conversation_id or phone_number
    session = RedisSession(conv_id)
    result = Runner.run_streamed(
        build_agent(),
        message,
        session=session,
        context=RunContext(phone_number=phone_number, channel=channel),
    )
    async for event in result.stream_events():
        if event.type == "raw_response_event":
            if isinstance(event.data, ResponseTextDeltaEvent) and event.data.delta:
                yield AgentStreamEvent(kind="text_delta", text=event.data.delta)
        elif event.type == "run_item_stream_event":
            item = getattr(event, "item", None)
            item_type = getattr(item, "type", None)
            if item_type == "tool_call_item":
                name = getattr(getattr(item, "raw_item", None), "name", None)
                yield AgentStreamEvent(kind="tool_call", tool_name=name)
            elif item_type == "tool_call_output_item":
                name = getattr(getattr(item, "raw_item", None), "name", None)
                yield AgentStreamEvent(kind="tool_output", tool_name=name, ok=True)


async def run_turn_stream(
    message: str,
    phone_number: str,
    conversation_id: str | None = None,
) -> AsyncIterator[str]:
    """Stream one guest message's reply as incremental text deltas (text/chat path).

    A text-only view over ``run_turn_events`` — yields just the reply ``text_delta``s so
    callers that don't care about tool events (e.g. streaming text) can pipe them straight on.
    Same trusted-context guarantees as ``run_turn``.
    """
    async for event in run_turn_events(message, phone_number, conversation_id):
        if event.kind == "text_delta" and event.text:
            yield event.text
